# Generated by Django 3.2.13 on 2022-04-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursus',
            name='scholar_year',
            field=models.CharField(default='0000-00001', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='cursus',
            name='year_from_bac',
            field=models.SmallIntegerField(default=0, help_text='year since le bac', null=True, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='student',
            name='comments',
            field=models.CharField(blank=True, default='', help_text='some comments about the student', max_length=255, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='student',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='x@y.z', help_text='phone number of the student', max_length=255, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='???', help_text='last name of the student', max_length=255, verbose_name='lastname'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0999999999', help_text='phone number of the student', max_length=10, verbose_name='phonenumber'),
        ),
    ]
